// Mock domain model for BitPolito Academy MVP.
// Kept verbose & technical-flavoured to read credibly inside the UI.

const ACADEMY_DATA = {
  user: { name: "L. Conti", handle: "lconti", role: "M.Sc. ICT Eng" },

  courses: [
    {
      id: "info-theory",
      code: "01TWZSM",
      title: "Information Theory & Coding",
      term: "2025/26 · Sem II",
      lecturer: "Prof. M. Re",
      docs: 14,
      indexed: 12,
      processing: 1,
      failed: 1,
      lastTouched: "2 hours ago",
      cover: "stripes",
      pinned: true,
    },
    {
      id: "applied-crypto",
      code: "02LSEOV",
      title: "Applied Cryptography",
      term: "2025/26 · Sem II",
      lecturer: "Prof. A. Basile",
      docs: 9,
      indexed: 9,
      processing: 0,
      failed: 0,
      lastTouched: "yesterday",
      cover: "stripes",
      pinned: true,
    },
    {
      id: "distsys",
      code: "01UDUOV",
      title: "Distributed Systems",
      term: "2025/26 · Sem II",
      lecturer: "Prof. G. Marchetto",
      docs: 22,
      indexed: 20,
      processing: 0,
      failed: 2,
      lastTouched: "3 days ago",
      cover: "stripes",
    },
    {
      id: "stoch-proc",
      code: "01TVNOV",
      title: "Stochastic Processes",
      term: "2024/25 · Sem I",
      lecturer: "Prof. R. Garello",
      docs: 6,
      indexed: 6,
      processing: 0,
      failed: 0,
      lastTouched: "last week",
      cover: "stripes",
    },
    {
      id: "comp-arch",
      code: "01OUZOV",
      title: "Computer Architecture",
      term: "2024/25 · Sem I",
      lecturer: "Prof. S. Di Carlo",
      docs: 11,
      indexed: 11,
      processing: 0,
      failed: 0,
      lastTouched: "Apr 2025",
      cover: "stripes",
    },
  ],

  // Documents inside the *active* course (info-theory).
  documents: [
    {
      id: "doc-01",
      name: "L05 — Source Coding Theorem.pdf",
      kind: "slides",
      pages: 42,
      sizeKB: 3120,
      uploadedAt: "Apr 28",
      state: "indexed",
      chunks: 318,
      parser: { ok: 0.97, ocr: false, lang: "en" },
    },
    {
      id: "doc-02",
      name: "L06 — Channel Capacity & AWGN.pdf",
      kind: "slides",
      pages: 38,
      sizeKB: 2740,
      uploadedAt: "Apr 28",
      state: "indexed",
      chunks: 286,
      parser: { ok: 0.96, ocr: false, lang: "en" },
    },
    {
      id: "doc-03",
      name: "Cover & Thomas — Ch.7 (excerpt).pdf",
      kind: "textbook",
      pages: 26,
      sizeKB: 4180,
      uploadedAt: "Apr 27",
      state: "indexed",
      chunks: 412,
      parser: { ok: 0.99, ocr: false, lang: "en" },
    },
    {
      id: "doc-04",
      name: "Past exam — 2024-07-12.pdf",
      kind: "exam",
      pages: 6,
      sizeKB: 480,
      uploadedAt: "Apr 27",
      state: "indexed",
      chunks: 47,
      parser: { ok: 0.94, ocr: true, lang: "it" },
    },
    {
      id: "doc-05",
      name: "Lecture notes — typicality (handwritten).pdf",
      kind: "notes",
      pages: 12,
      sizeKB: 8820,
      uploadedAt: "Apr 30",
      state: "processing",
      progress: 0.62,
      stage: "chunking → embed",
      chunks: null,
      parser: { ok: 0.81, ocr: true, lang: "en" },
    },
    {
      id: "doc-06",
      name: "L07 — Rate-Distortion (annotated).pdf",
      kind: "slides",
      pages: 31,
      sizeKB: 3990,
      uploadedAt: "Apr 30",
      state: "uploading",
      progress: 0.38,
      chunks: null,
      parser: null,
    },
    {
      id: "doc-07",
      name: "Tutorial 04 — Huffman exercises.pdf",
      kind: "exercises",
      pages: 4,
      sizeKB: 220,
      uploadedAt: "Apr 30",
      state: "failed",
      error: "Parser: malformed xref table at byte 184902. Re-export from source.",
      chunks: null,
      parser: null,
    },
    {
      id: "doc-08",
      name: "L04 — Entropy & Mutual Information.pdf",
      kind: "slides",
      pages: 36,
      sizeKB: 2510,
      uploadedAt: "Apr 24",
      state: "indexed",
      chunks: 274,
      parser: { ok: 0.98, ocr: false, lang: "en" },
    },
  ],

  // The currently-open document, used by the source viewer.
  // We model 4 "pages" (slide thumbnails) with parsed structure.
  openDoc: {
    id: "doc-01",
    name: "L05 — Source Coding Theorem.pdf",
    pages: 42,
    activePage: 17,
    outline: [
      { id: "s1", label: "1. Information & entropy",          page: 2 },
      { id: "s2", label: "2. Typical sequences",              page: 9 },
      { id: "s3", label: "3. AEP — Asymptotic Equipartition", page: 14 },
      { id: "s4", label: "4. Source coding theorem",          page: 17, active: true },
      { id: "s5", label: "5. Achievability proof",            page: 22 },
      { id: "s6", label: "6. Converse",                       page: 28 },
      { id: "s7", label: "7. Examples — Bernoulli source",    page: 33 },
      { id: "s8", label: "8. Limits & extensions",            page: 38 },
    ],
    // Slide-17 parsed content for preview + citation anchoring
    parsed: {
      title: "Source Coding Theorem (Shannon, 1948)",
      bullets: [
        "Statement: For an i.i.d. source with entropy H(X), there exists a uniquely decodable code with rate R ≥ H(X). Conversely, any code with R < H(X) has error probability bounded away from 0 as n → ∞.",
        "Construction relies on the typical set T_ε^(n): for n large, P(T_ε^(n)) ≥ 1 − ε and |T_ε^(n)| ≤ 2^{n(H(X)+ε)}.",
        "Encoder: index sequences in T_ε^(n) with ⌈n(H+ε)⌉ bits; assign a single error symbol to atypical sequences.",
        "Decoding error: P_e ≤ ε + 2^{−nε/2} for sufficiently large n (Chebyshev on log-likelihood).",
      ],
      formula: "n · H(X)  ≤  E[ ℓ(C) ]  ≤  n · H(X) + 1",
      cap: "Fig. 5.4 — Operational meaning of H(X) as the minimum rate.",
    },
  },

  studyActions: [
    { id: "explain",     label: "Explain concept",        sub: "Step-by-step derivation",         shortcut: "E", glyph: "Σ" },
    { id: "summarize",   label: "Summarize section",      sub: "Compressed, source-anchored",     shortcut: "S", glyph: "≡" },
    { id: "passages",    label: "Retrieve passages",      sub: "Top-k from evidence pack",        shortcut: "R", glyph: "⌖" },
    { id: "open",        label: "Open questions",         sub: "Conceptual prompts to test depth",shortcut: "O", glyph: "?" },
    { id: "quiz",        label: "Quiz questions",         sub: "Multiple-choice with rationale",  shortcut: "Q", glyph: "▢" },
    { id: "oral",        label: "Oral-exam prompts",      sub: "Adversarial, edge-case driven",   shortcut: "L", glyph: "◉" },
    { id: "derive",      label: "Derive / prove",         sub: "Proof scaffolding from sources",  shortcut: "D", glyph: "∂" },
    { id: "compare",     label: "Compare definitions",    sub: "Reconcile across sources",        shortcut: "C", glyph: "⇌" },
  ],

  // Mock evidence pack for the active study request.
  evidence: [
    {
      id: "ev-1",
      doc: "doc-01", docName: "L05 — Source Coding Theorem.pdf",
      anchor: "p.17 · §4",
      score: 0.918,
      rerank: 0.871,
      kind: "slide",
      preview: "…the typical set T_ε^(n) satisfies P(T_ε^(n)) ≥ 1 − ε and |T_ε^(n)| ≤ 2^{n(H(X)+ε)}, which is the cornerstone of the achievability part…",
    },
    {
      id: "ev-2",
      doc: "doc-03", docName: "Cover & Thomas — Ch.7 (excerpt).pdf",
      anchor: "p.62 · Thm 5.4.1",
      score: 0.902,
      rerank: 0.864,
      kind: "textbook",
      preview: "…the source coding theorem states that any rate above the entropy is achievable, and any rate below entropy is not. Equivalently, expected codeword length L satisfies H(X) ≤ L < H(X) + 1…",
    },
    {
      id: "ev-3",
      doc: "doc-01", docName: "L05 — Source Coding Theorem.pdf",
      anchor: "p.22 · §5",
      score: 0.876,
      rerank: 0.812,
      kind: "slide",
      preview: "…achievability proof — encode sequences in the typical set with ⌈n(H+ε)⌉ bits and assign a single fail-symbol to the atypical complement…",
    },
    {
      id: "ev-4",
      doc: "doc-08", docName: "L04 — Entropy & Mutual Information.pdf",
      anchor: "p.11 · Def 3.2",
      score: 0.788,
      rerank: 0.741,
      kind: "slide",
      preview: "…entropy H(X) = −Σ p(x) log p(x) is the unique (up to scale) measure satisfying continuity, monotonicity and the chain rule…",
    },
    {
      id: "ev-5",
      doc: "doc-04", docName: "Past exam — 2024-07-12.pdf",
      anchor: "Q.3 · part (b)",
      score: 0.701,
      rerank: 0.683,
      kind: "exam",
      preview: "…compute the minimum expected codeword length for a Bernoulli(p=0.1) source over blocks of length n=4 and compare with H(X)…",
      lang: "it",
    },
  ],

  // Mock generated answer for the active study request.
  generated: {
    action: "explain",
    query: "Explain the Source Coding Theorem and why the typical set bounds the achievable rate.",
    timestamp: "just now",
    tokensIn: 4218,
    tokensOut: 612,
    model: "qvac-rag-mix · sonnet-4 fallback",
    body: [
      {
        h: "Statement",
        p: [
          { t: "For an i.i.d. source with entropy ", c: null },
          { t: "H(X)", c: null, code: true },
          { t: ", a code with rate ", c: null },
          { t: "R > H(X)", c: null, code: true },
          { t: " is achievable, while any rate ", c: null },
          { t: "R < H(X)", c: null, code: true },
          { t: " has error probability bounded away from zero", c: "ev-1" },
          { t: " as block length grows. The bound is tight: ", c: null },
          { t: "H(X) ≤ E[ℓ(C)] < H(X) + 1", c: "ev-2", code: true },
          { t: ".", c: null },
        ],
      },
      {
        h: "Why the typical set",
        p: [
          { t: "The achievability argument hinges on the typical set ", c: null },
          { t: "T_ε^(n)", c: null, code: true },
          { t: ": for large enough ", c: null },
          { t: "n", c: null, code: true },
          { t: ", almost all probability mass concentrates on a vanishingly-small fraction of sequences", c: "ev-1" },
          { t: ". Concretely ", c: null },
          { t: "|T_ε^(n)| ≤ 2^{n(H+ε)}", c: "ev-1", code: true },
          { t: ", which gives a direct construction: index typical sequences with ", c: null },
          { t: "⌈n(H+ε)⌉", c: null, code: true },
          { t: " bits and reserve a single fail-symbol for the atypical complement", c: "ev-3" },
          { t: ".", c: null },
        ],
      },
      {
        h: "Why R < H(X) fails",
        p: [
          { t: "If R < H(X), the code can index at most ", c: null },
          { t: "2^{nR}", c: null, code: true },
          { t: " distinct sequences, but typical sequences number at least ", c: null },
          { t: "2^{n(H−ε)}", c: null, code: true },
          { t: ". For small enough ε the inequality forces a constant fraction of typical sequences to collide, so ", c: null },
          { t: "P_e", c: null, code: true },
          { t: " is bounded below by a non-vanishing constant — see the converse on slide 28", c: "ev-1" },
          { t: ".", c: null },
        ],
      },
    ],
    flags: [
      { kind: "ok",   label: "All claims grounded in 5 passages" },
      { kind: "warn", label: "1 passage in Italian — translated inline" },
    ],
  },
};

window.ACADEMY_DATA = ACADEMY_DATA;
